version: '2'
services:
  web:
    build:
      context: .
    image: launchpad-mobx
    volumes:
      - .:/code
    environment:
      NODE_ENV: production
  proxy:
    restart: always
    image: nginx:alpine
    volumes:
      - ./www/nginx.conf:/etc/nginx/nginx.conf
    links:
      - web
    ports:
      - "80:80"
      - "443:443"
