version: '2'
services:
  web:
    build:
      context: .
    image: launchpad-mobx
    volumes:
      - .:/code
  proxy:
    restart: always
    image: nginx
    volumes:
      - ./www:/usr/share/nginx/html
    links:
      - web
    ports:
      - "80:80"
      - "443:443"
